### ISSUE TITLE
Proxies do not work

### ISSUE THREAD

**Issue by moeinovic** [thehamkercat/Python_ARQ#3]

**Comment by TheHamkerCat** [comment]
What do you mean?

**Comment by moeinovic** [comment]
> 

The proxies I receive from arq are dead and even the port is closed

**Comment by TheHamkerCat** [comment]
Replace the IP with any address from this list, omit the port if you want, it will work.

<html>
<body>


Country | Location | Address
-- | -- | --
Australia | Sydney | syd.socks.ipvanish.com
Brazil | Sao Paulo | gig.socks.ipvanish.com
Canada | Toronto | tor.socks.ipvanish.com
France | Paris | par.socks.ipvanish.com
Germany | Frankfurt | fra.socks.ipvanish.com
Italy | Milan | lin.socks.ipvanish.com
Japan | Tokyo | nrt.socks.ipvanish.com
Netherlands | Amsterdam | ams.socks.ipvanish.com
Poland | Warsaw | waw.socks.ipvanish.com
Portugal | Lisbon | lis.socks.ipvanish.com
Singapore | Singapore | sin.socks.ipvanish.com
Spain | Madrid | mad.socks.ipvanish.com
Sweden | Stockholm | sto.socks.ipvanish.com
United Kingdom | London | lon.socks.ipvanish.com
United States | Ashburn | iad.socks.ipvanish.com
United States | Atlanta | atl.socks.ipvanish.com
United States | Boston | bos.socks.ipvanish.com
United States | Charlotte | clt.socks.ipvanish.com
United States | Chicago | chi.socks.ipvanish.com
United States | Dallas | dal.socks.ipvanish.com
United States | Denver | den.socks.ipvanish.com
United States | Los Angeles | lax.socks.ipvanish.com
United States | Miami | mia.socks.ipvanish.com
United States | New Orleans | msy.socks.ipvanish.com
United States | New York | nyc.socks.ipvanish.com
United States | Phoenix | phx.socks.ipvanish.com
United States | Seattle | sea.socks.ipvanish.com


</body>
</html>
